### ISSUE TITLE
how to display output in the app?

### ISSUE THREAD

**Issue by kdevda** [ajohnson388/DLParser-Swift#5]
hey there, I found that all Camera is perfectly reading the the DL Barcode, but the output is returned in the Output console of the XCode. How can I display the output in the app itself?

Really appreciate your help on this.

thank you!

KD

**Comment by ajohnson388** [comment]
There are no plans to output data within the example app itself, only in the console. It is meant to test the efficacy of the parser with actual driver licenses, and is not intended for use outside of development.

Andy
